# fly.toml app configuration file

app = "nutritrack-api"
primary_region = "sin"

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1
  
[mounts]
source = "nutritrack_data"
destination = "/app/data"

[env]
  HOST = "0.0.0.0"
  PORT = "8000"
  LOG_LEVEL = "INFO"
  LOG_TO_FILE = "false"
  PYTHONUNBUFFERED = "1"
